---
database:
  # will also perform partial matches
  ignore_tables:
    - qs_
    - proximities
    - task_activities_backup_
    - backup
    - vw_
    - peq_admin
    - spire_
    - tool_
    - goallists
    - mercbuffs
    - merc_
    - mercs
    - new_table
#    - perl_event_export_settings
    - group_leader
  table_connections:
    eqemu_content:
      - aa_ability
      - aa_rank_effects
      - aa_rank_prereqs
      - aa_ranks
      - adventure_template
      - adventure_template_entry
      - adventure_template_entry_flavor
      - alternate_currency
      - auras
      - base_data
      - blocked_spells
      - books
      - char_create_combinations
      - char_create_point_allocations
      - damageshieldtypes
      - doors
      - faction_base_data
      - faction_list
      - faction_list_mod
      - fishing
      - forage
      - global_loot
      - goallists
      - graveyard
      - grid
      - grid_entries
      - ground_spawns
      - horses
      - items
      - ldon_trap_entries
      - ldon_trap_templates
      - lootdrop
      - lootdrop_entries
      - loottable
      - loottable_entries
      - merchantlist
      - npc_emotes
      - npc_faction
      - npc_faction_entries
      - npc_scale_global_base
      - npc_spells
      - npc_spells_effects
      - npc_spells_effects_entries
      - npc_spells_entries
      - npc_types
      - npc_types_tint
      - object
      - pets
      - pets_equipmentset
      - pets_equipmentset_entries
      - proximities
      - skill_caps
      - spawn2
      - spawn_conditions
      - spawnentry
      - spawngroup
      - spells_new
      - start_zones
      - starting_items
      - task_activities
      - tasks
      - tasksets
      - tradeskill_recipe
      - tradeskill_recipe_entries
      - traps
      - tribute_levels
      - tributes
      - veteran_reward_templates
      - zone
      - zone_points
    eqemu_logs:
      - player_event_log_settings
      - player_event_logs